# Copyright IBM Corp. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
version: '2'
networks:
  kajmak:
services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/--HERE--
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - kajmak
  
  ca.org2.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/--HERE--
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:
      - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - kajmak

  ca.org3.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/--HERE--
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3
    networks:
      - kajmak

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./config/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/crypto/peer0Org1
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/hyperledger/crypto/peer1Org1
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/crypto/peer0Org2
      - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/hyperledger/crypto/peer1Org2
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/:/etc/hyperledger/crypto/peer0Org3
      - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/:/etc/hyperledger/crypto/peer1Org3
    networks:
      - kajmak

peer0.org1.example.com:
  container_name: peer0.org1.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer0.org1.example.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  command: peer node start
  ports:
    - 7051:7051
    - 7053:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/crypto/users/org1
    - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/crypto/users/org2
  depends_on:
    - orderer.example.com
  networks:
    - kajmak
peer1.org1.example.com:
  container_name: peer1.org1.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer1.org1.example.com
    - CORE_PEER_LOCALMSPID=Org1MSP
    - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  ports:
    - 7056:7051
    - 7058:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/crypto/users
  depends_on:
    - orderer.example.com
  networks:
    - kajmak

peer0.org2.example.com:
  container_name: peer0.org2.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer0.org2.example.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  ports:
    - 8051:7051
    - 8053:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/crypto/users
  depends_on:
    - orderer.example.com
  networks:
    - kajmak

peer1.org2.example.com:
  container_name: peer1.org2.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer1.org2.example.com
    - CORE_PEER_LOCALMSPID=Org2MSP
    - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  ports:
    - 8056:7051
    - 8058:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/crypto/users
  depends_on:
    - orderer.example.com
  networks:
    - kajmak

peer0.org3.example.com:
  container_name: peer0.org3.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer0.org3.example.com
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  ports:
    - 9051:7051
    - 9053:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/crypto/users
  depends_on:
    - orderer.example.com
  networks:
    - kajmak

peer1.org3.example.com:
  container_name: peer1.org3.example.com
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ID=peer1.org3.example.com
    - CORE_PEER_LOCALMSPID=Org3MSP
    - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
    - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peer/
    - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_kajmak
    - CORE_LOGGING_PEER=debug
    - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
  working_dir: /opt/gopath/src/github.com/hyperledger/fabric
  ports:
    - 9056:7051
    - 9058:7053
  volumes:
    - /var/run/:/host/var/run/
    - ./config/:/etc/hyperledger/configtx
    - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/crypto/peer
    - ./crypto-config/peerOrganizations/org3.example.com/users:/etc/hyperledger/crypto/users
  depends_on:
    - orderer.example.com
  networks:
    - kajmak